# Generated by Django 4.2.11 on 2024-03-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_choices',
            field=models.CharField(choices=[('test1', 'test1'), ('test2', 'test2'), ('test3', 'test3')], default='test1', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_participants',
            field=models.IntegerField(),
        ),
    ]
